### ISSUE TITLE
Reduce the footprint of the NuvlaBox Engine

### ISSUE THREAD

**Issue by schaubl** [nuvlabox/deployment#47]
Currently the NB Engine has a minimum requirement of 1 GB of RAM.
It is composed of minimum 10 containers.

To continue supporting very small hardware like RaspberryPi and even RPi Zero, we should have a way to deploy a "tiny" version of the NB Engine.

To achieve that goal, I would suggest that we: 
- separate some features from the core so that we can make them optional (but they can still be included by default).
- try to decouple some containers.
- assess the resource consumption of every containers of the NB engine and see if some can be reduced or merged.

**separate some features from the core**
I can think about the _datagateway_, the _security scan_, the _vpn_ features. 
For the _datagateway_, if the feature is not needed, we can get rid of the `datagateway` and `mosquitto` containers. 
For the _vpn_, if the NB has no VPN configured, the `vpn-client` container should not be started and maybe the container `network-manager` is not required.

**Comment by cjdcordeiro** [comment]
already done for v2.0: https://media.sixsq.com/hs-fs/hubfs/Blog%20post%20images/blog_nbed.png?width=3365&name=blog_nbed.png

further optimizations need now to happen on a per component basis
