### ISSUE TITLE
Add an environment variable to inject custom configuration in the VPN client configuation file

### ISSUE THREAD

**Issue by schaubl** [nuvlabox/deployment#61]

**Comment by cjdcordeiro** [comment]
@schaubl please share what the env var should be named and where it should go inside the conf file

**Comment by schaubl** [comment]
For example `VPN_CONFIG_EXTRA` and it can be added at the end of the openvpn configuration file.

**Comment by cjdcordeiro** [comment]
and what would that extra configuration look like?

**Comment by schaubl** [comment]
OpenVPN configuration lines.
For example:
```
route-nopull
route 10.0.128.0 255.255.128.0
client-nat dnat 172.30.0.0 255.255.0.0 10.30.0.0
```
